version: '3'

services:
  redis:
    container_name: redis
    hostname: redis
    build: .
    ports:
    - "6379:6379"
    volumes:
    - ./data:/data ## de querer tener persistencia

  redis-commander:
      container_name: redis-commander
      hostname: redis-commander
      image: rediscommander/redis-commander@sha256:4d203e794be65c82a1e4d2785b7c717ae9b66485658e307a413c077b44887cd6
      restart: always
      environment:
      - REDIS_HOSTS=local:redis:6379
      ports:
      - "8081:8081"
      depends_on:
      - redis