version: '3'

services:
  redis:
      image: redis
      ports:
      - "6379:6379"
      command: bash -c "echo 'heyyyyy' && redis-server " 
      
  redis-commander:
     image: rediscommander/redis-commander:latest
     environment:
       - REDIS_HOSTS=local:redis:6379
       - HTTP_USER=root
       - HTTP_PASSWORD=qwerty
     ports:
       - "8081:8081"
     depends_on:
       - redis
 