version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    build: ./redis
    ports:
    - "6379:6379"
    volumes:
    - ./data:/data ## de querer tener persistencia

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=redis
    ports:
    - "8081:8081"